Web/TravelBooking.Web/Areas/Administration/Controllers/DashboardController.cs
namespace TravelBooking.Web.Areas.Administration.Controllers
{
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Mvc;
    using TravelBooking.Services.Data.Bookings;
    using TravelBooking.Services.Data.Users;
    using TravelBooking.Web.Infrastructure.Extensions;
    using TravelBooking.Web.ViewModels.Bookings;
    using TravelBooking.Web.ViewModels.Users;

    public class DashboardController : AdministrationController
    {
        private readonly IBookingsService bookingsService;
        private readonly IUsersService usersService;

        public DashboardController(
            IBookingsService bookingsService,
            IUsersService usersService)
        {
            this.bookingsService = bookingsService;
            this.usersService = usersService;
        }

        public IActionResult Index()
        {
            return this.View();
        }

        public async Task<IActionResult> Bookings()
        {
            var viewModel = await this.bookingsService.GetAllAsync<BookingViewModel>();
            return this.View(viewModel);
        }

        public async Task<IActionResult> Users()
        {
            var viewModel = await this.usersService.GetAllAsync<UserViewModel>(this.User.GetUserId());
            return this.View(viewModel);
        }

        public async Task<IActionResult> Remove(string id)
        {
            await this.bookingsService.DeleteBookingAsync(id);
            return this.RedirectToAction(nameof(this.Bookings));
        }
    }
}

Web/TravelBooking.Web/Controllers/BookingsController.cs
namespace TravelBooking.Web.Controllers
{
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Mvc;
    using TravelBooking.Common;
    using TravelBooking.Services.Data.Bookings;
    using TravelBooking.Web.Infrastructure.Attributes;
    using TravelBooking.Web.Infrastructure.Extensions;
    using TravelBooking.Web.ViewModels.Bookings;

    public class BookingsController : BaseController
    {
        private readonly IBookingsService bookingsService;

        public BookingsController(IBookingsService bookingsService)
        {
            this.bookingsService = bookingsService;
        }

        public IActionResult Travel()
        {
            this.TempData[GlobalConstants.ReturnUrlKey] = this.ReturnUrl;
            return this.View();
        }

        public IActionResult Animal()
        {
            this.TempData[GlobalConstants.ReturnUrlKey] = this.ReturnUrl;
            return this.View();
        }

        public IActionResult Baggage()
        {
            this.TempData[GlobalConstants.ReturnUrlKey] = this.ReturnUrl;
            return this.View();
        }

        public IActionResult Vehicle()
        {
            this.TempData[GlobalConstants.ReturnUrlKey] = this.ReturnUrl;
            return this.View();
        }

        [HttpPost]
        [SetTempDataErrors(GlobalConstants.ModelStateErrorKey)]
        public async Task<IActionResult> Booking(BookingInputBaseModel model, string returnUrl)
        {
            if (!this.ModelState.IsValid)
            {
                return this.Redirect(returnUrl);
            }

            model.ApplicationUserId = this.User.GetUserId();
            await this.bookingsService.CreateBookingAsync(model);
            return this.RedirectToAction(nameof(this.SuccessBooking));
        }

        public IActionResult SuccessBooking()
        {
            return this.View();
        }
    }
}

Web/TravelBooking.Web/Views/Shared/_BookingPartial.cshtml
@model BookingInputBaseModel

<input type="hidden" value="@this.TempData[GlobalConstants.ReturnUrlKey]" name="returnUrl" />
<div class="text-danger">@this.TempData[GlobalConstants.ModelStateErrorKey]</div>
<div class="row">
    <div class="col-md-6 margin-b">
        <div class="input-group">
            <input asp-for="FirstName" class="form-control border-radius border-right" placeholder="Име" required>
            <span asp-validation-for="FirstName" class="text-danger"></span>
            <span class="input-group-addon  border-radius custom-addon">
                <i class="ion-person"></i>
            </span>
        </div>
    </div>
    <div class="col-md-6">
        <div class="input-group">
            <input asp-for="LastName" class="form-control border-radius border-right" placeholder="Фамиля" required>
            <span asp-validation-for="FirstName" class="text-danger"></span>
            <span class="input-group-addon  border-radius custom-addon">
                <i class="ion-person"></i>
            </span>
        </div>
    </div>
</div>

<div class="input-group" style="margin-top: 10px">
    <input asp-for="PhoneNumber" class="form-control border-radius border-right" type="tel" placeholder="Телефон">
    <span asp-validation-for="PhoneNumber" class="text-danger"></span>
    <span class="input-group-addon  border-radius custom-addon">
        <i class="ion-ios-telephone"></i>
    </span>
</div>

<div class="input-group" style="margin-top: 10px">
    <textarea asp-for="CustomerNote" class="form-control border-radius border-right" rows="5" placeholder="Бележка към заявката. Полето не е задължително"></textarea>
    <span asp-validation-for="CustomerNote" class="text-danger"></span>
    <span class="input-group-addon  border-radius custom-addon">
        <i class="ion-android-bookmark"></i>
    </span>
</div>

<div class="row">
    <div class="col-md-6">
        <h5 style="color: black">От</h5>
        <div class="input-group margin-b">
            <input asp-for="OriginAddress" class="form-control border-radius border-right message" placeholder="От Адрес">
            <span asp-validation-for="OriginAddress" class="text-danger"></span>
            <span class="input-group-addon border-radius custom-addon">
                <i class="ion-android-home"></i>
            </span>
        </div>
        <div class="input-group">
            <input asp-for="OriginCity" class="form-control border-radius border-right message" placeholder="От Град">
            <span asp-validation-for="OriginCity" class="text-danger"></span>
            <span class="input-group-addon border-radius custom-addon">
                <i class="ion-location"></i>
            </span>
        </div>
        <div class="input-group">
            <select asp-for="OriginCountry" class="form-control border-radius border-right message" placeholder="От Държава">
                <option>България</option>
                <option>Германия</option>
                <option>Австрия</option>
                <option>Унгария</option>
                <option>Нидерландия</option>
                <option>Белгия</option>
                <option>Дания</option>
            </select>
            <span class="input-group-addon border-radius custom-addon">
                <i class="ion-paper-airplane"></i>
            </span>
        </div>
    </div>
    <div class="col-md-6">
        <h5 style="color: black">До</h5>
        <div class="input-group">
            <input asp-for="DestinationAddress" class="form-control border-radius border-right message" placeholder="До Адрес">
            <span asp-validation-for="DestinationAddress" class="text-danger"></span>
            <span class="input-group-addon border-radius custom-addon">
                <i class="ion-android-home"></i>
            </span>
        </div>
        <div class="input-group">
            <input asp-for="DestinationCity" class="form-control border-radius border-right message" placeholder="До Град">
            <span asp-validation-for="DestinationCity" class="text-danger"></span>
            <span class="input-group-addon border-radius custom-addon">
                <i class="ion-location"></i>
            </span>
        </div>
        <div class="input-group">
            <select asp-for="DestinationCountry" class="form-control border-radius border-right message" placeholder="От Град">
                <option>България</option>
                <option>Германия</option>
                <option>Австрия</option>
                <option>Унгария</option>
                <option>Нидерландия</option>
                <option>Белгия</option>
                <option>Дания</option>
            </select>
            <span class="input-group-addon border-radius custom-addon">
                <i class="ion-paper-airplane"></i>
            </span>
        </div>
    </div>
</div>

Web/TravelBooking.Web/Views/Shared/_Layout.cshtml
@using TravelBooking.Common
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.3.0/css/all.css">
    <title>@this.ViewData[@GlobalConstants.Title] - @GlobalConstants.SystemName</title>
    <link rel="stylesheet" href="~/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/about.css">
    <link rel="stylesheet" href="~/css/contact.css">
    <link rel="stylesheet" href="~/css/flexslider.css">
    <link rel="stylesheet" href="~/css/ionicons.css">
    <link rel="stylesheet" href="~/css/ionicons.min.css">
    <link rel="stylesheet" href="~/css/main.css">
    <link rel="stylesheet" href="~/css/owl.carousel.css">
    <link rel="stylesheet" href="~/css/owl.theme.css">
    <link rel="stylesheet" href="~/css/section.css">
    <link rel="stylesheet" href="~/css/services.css">
    <link rel="stylesheet" href="~/css/site.css">
</head>
<body>
    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-action="Index" asp-controller="Home" asp-area="" class="navbar-brand" title="HOME"><i class="ion-paper-airplane"></i> euro <span>travel</span></a>
            </div> <!-- /.navbar-header -->
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li><a asp-action="Index" asp-controller="Home" asp-area="">Home</a></li>
                    <li class="dropdown">
                        <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" aria-haspopup="true" aria-expanded="false">
                            Запази за
                            <i class="fa fa-caret-down"></i>
                        </a>
                        <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                            <a class="dropdown-item" asp-action="Travel" asp-controller="Bookings" asp-area="">Пътуване</a>
                            <a class="dropdown-item" asp-action="Baggage" asp-controller="Bookings" asp-area="">Багаж</a>
                            <a class="dropdown-item" asp-action="Animal" asp-controller="Bookings" asp-area="">Домашен любимец</a>
                            <a class="dropdown-item" asp-action="Vehicle" asp-controller="Bookings" asp-area="">Мотор</a>
                        </div>
                    </li>
                    @if (!this.User.Identity.IsAuthenticated)
                    {
                        <li><a asp-area="Identity" asp-page="/Account/Login">Вход</a></li>
                        <li><a asp-area="Identity" asp-page="/Account/Register">Регистрация</a></li>
                    }
                    else
                    {
                        @if (this.User.IsInRole(GlobalConstants.AdministratorRoleName))
                        {
                            <li><a asp-action="Index" asp-controller="Dashboard" asp-area="@GlobalConstants.AdministrationArea">Админ</a></li>
                        }

                        <li><a asp-area="Identity" asp-page="/Account/Logout">Изход</a></li>
                    }
                </ul> <!-- /.nav -->
            </div><!-- /.navbar-collapse -->
        </div><!-- /.container -->
    </nav>

    <partial name="_CookieConsentPartial" />

    @this.RenderBody()

    <!-- /.contacts -->
    <section class="contacts section-wrapper">
        <div class="container">
            <div class="row">
                <div class="col-sm-6" style="margin-bottom: 20px">
                    <a target="_blank" href="https://www.facebook.com/Europe.Transporter/?modal=admin_todo_tour&notif_id=1674158976829818&notif_t=page_invite&ref=notif" style="font-size: 40px; text-decoration: none;">
                        <div class="contact">
                            <div class="contact-icon">
                                <i class="ion-social-facebook"></i>
                            </div>
                            <div class="contact-detail" style="font-size: 40px; padding-top: 103px;">
                                Facebook
                            </div>
                        </div> <!-- /.contact -->
                    </a>
                </div> <!-- /.col-sm-4 -->
                <div class="col-sm-6" style="margin-bottom: 20px">
                    <a href="tel:00879886033" style="text-decoration: none">
                        <div class="contact">
                            <div class="contact-icon">
                                <i class="ion-ios-telephone"></i>
                            </div>
                            <div class="contact-detail" style="font-size: 40px; padding-top: 103px;">
                                0879886033
                            </div>
                        </div> <!-- /.contact -->
                    </a>
                </div> <!-- /.col-sm-4 -->
            </div> <!-- /.row -->
        </div> <!-- /.container -->
    </section>
    <!-- /.contacts -->

        <!-- Your bottom bar content here -->
        <footer class="footer">
            <div class="container">
                <div class="row">
                    <div class="col-xs-4">
                        <div class="text-left">
                            &copy; Copyright Euro Travels
                        </div>
                    </div>
                    <div class="col-xs-4">
                    </div>
                    <div class="col-xs-4">
                        <div class="top">
                            <a href="#header">
                                <i class="ion-arrow-up-b"></i>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </footer>

    <script src="~/lib/jquery/dist/jquery.min.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.min.js" asp-append-version="true"></script>
    <script src="~/js/site.min.js" asp-append-version="true"></script>
    <script src="~/js/jquery-1.11.2.min.js"></script>
    <script src="~/js/bootstrap.min.js"></script>
    <script src="~/js/owl.carousel.min.js"></script>
    <script src="~/js/contact.js"></script>
    <script src="~/js/jquery.flexslider.js"></script>
    <script src="~/js/script.js"></script>

    @await this.RenderSectionAsync("Scripts", required: false)

</body>
</html>